version: 1

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

before:
  hooks:
    - go mod tidy
    # - go generate ./...  # Leaving for future use.

builds:
  - goos:
      - darwin
      - linux

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Produce a stock checksum file.
checksum: {}

dockers:
  - dockerfile: build/package/Containerfile
    image_templates:
      - spacez320/{{ .ProjectName }}:latest
      - spacez320/{{ .ProjectName }}:{{ .Version }}
    use: podman
